### ISSUE TITLE
8Q seems to be abandoned

### ISSUE THREAD

**Issue by InfamousPlatypus** [qosf/awesome-quantum-software#117]
I'm a contributer to 8Q, it's found in experimental quantum computing. As much as I'd like to seeing moving forward I'm not seeing anything from the maintainer in any communication channels.
Should this be marked as abandoned?

**Comment by dlyongemallo** [comment]
Yes, if there's 2+ years of inactivity and no contact from the maintainers, it should be moved to the abandoned section.

**Comment by InfamousPlatypus** [comment]
Yah, it's been two years.
